# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/no-phux/phux"
  url "https://github.com/no-phux/phux/releases/download/v0.32.0/phux-v0.32.0-aarch64-apple-darwin.tar.gz"
  sha256 "5424df85c07ebc71fe689d7aabdbdfc61bc36976382fee24b621094b4494af53"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    depends_on arch: :arm64
  end

  on_linux do
    on_intel do
      url "https://github.com/no-phux/phux/releases/download/v0.32.0/phux-v0.32.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "abf640e29d4501856d5cdb2c3a472d1f46b16714baddc604dc95c81cc1cf59b3"
    end
    on_arm do
      url "https://github.com/no-phux/phux/releases/download/v0.32.0/phux-v0.32.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "34f782210a3cde204c6b36996baf5f83d40b6481ed510121df554233375c6a75"
    end
  end

  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
