# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/no-phux/phux"
  url "https://github.com/no-phux/phux/releases/download/v0.29.0/phux-v0.29.0-aarch64-apple-darwin.tar.gz"
  sha256 "972309ad615483b82d6a49f97735727ada410f7889e8137ce996433b7a53c846"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    depends_on arch: :arm64
  end

  on_linux do
    on_intel do
      url "https://github.com/no-phux/phux/releases/download/v0.29.0/phux-v0.29.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "27432b486080a5878245f482f83b7436b4fd1516e75c98331f02ba5468206a8f"
    end
    on_arm do
      url "https://github.com/no-phux/phux/releases/download/v0.29.0/phux-v0.29.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8d695245c2ebc817e5da233be39abd18e8a0e0fb3efb5e380642b69d3c3091e5"
    end
  end

  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
