# This file is generated by scripts/gen-formula.sh (phux release workflow).
# Do not edit by hand.
class Phux < Formula
  desc "Libghostty-backed terminal control plane (not tmux)"
  homepage "https://github.com/no-phux/phux"
  url "https://github.com/no-phux/phux/releases/download/v0.33.0/phux-v0.33.0-aarch64-apple-darwin.tar.gz"
  sha256 "13e444e6f607783579a5c411bb47e022350ca2399510557f0bf4cf5ce4b79c05"
  license any_of: ["MIT", "Apache-2.0"]

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    depends_on arch: :arm64
  end

  on_linux do
    on_intel do
      url "https://github.com/no-phux/phux/releases/download/v0.33.0/phux-v0.33.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "57ad8d25bbbaaadc188bd02a17e24875c0f0112d9f5ab8a4dd59ec25351c69a5"
    end
    on_arm do
      url "https://github.com/no-phux/phux/releases/download/v0.33.0/phux-v0.33.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "74ddb5496430bf4dacddf32b94b71beaf631f4f7b85e83106f191b4be4dc8ead"
    end
  end

  def install
    bin.install "phux"
    bin.install "phux-mcp"
  end

  test do
    assert_path_exists bin/"phux-mcp"
    assert_predicate bin/"phux-mcp", :executable?
    assert_match version.to_s, shell_output("#{bin}/phux --version 2>&1")
  end
end
